const mongoose = require('mongoose')

const user = new mongoose.Schema({
    Name:{
        type:String,
        required:true
    },
    Title:{
        type:String,
        default:""
    },
    Linedin:{
        type:String,
        default:""
    },
    github:{
        type:String,
        default:""
    },
    email:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    company:{
        type:String,
        default:""
    },
    certificateLink:{
        type:String,
        default:""
    },
    location:{
        type:String,
        default:""
    },
    startDate:{
        type:String,
        default:""
    },
    endDate:{
        type:String,
        default:""
    },
    workExperience:{
        type:String,
        default:""
    },
    projectTitle:{
        type:String,
        default:""
    },
    overview:{
        type:String,
        default:""
    },
    deploymentLink:{
        type:String,
        default:""
    },
    githubLink:{
        type:String,
        default:""
    },
    projectDescription:{
        type:String,
        default:""
    },
    courseName:{
        type:String,
        default:""
    },
    college:{
        type:String,
        default:""
    },
    startDateCollege:{
        type:String,
        default:""
        },
    endDateCollege:{
        type:String,
        default:""
    },
    achievement1:{
        type:String,
        default:""
    },
    achievement2:{
        type:String,
        default:""
    },
    achievement3:{
        type:String,
        default:""
    },
    achievement4:{
        type:String,
        default:""
    },
    skill1:{
        type:String,
        default:""
    },
    skill2:{
        type:String,
        default:""
    },
    skill3:{
        type:String,
        default:""
    },
    skill4:{
        type:String,
        default:""
    },
    language1:{
        type:String,
        default:""
    },
    language2:{
        type:String,
        default:""
    },
    language3:{
        type:String,
        default:""
    },
    language4:{
        type:String,
        default:""
    },
    professionalSummary:{
        type:String,
        default:""
    },
    resumeType:{
        type:Number,
        default:0
    },
    date:{
        type:Date,
        default: Date.now
    }
   
})
mongoose.model("User", user)